### ISSUE TITLE
can Ranges constructor be made public?

### ISSUE THREAD

**Issue by ebremer** [davidmoten/hilbert-curve#11]
https://github.com/davidmoten/hilbert-curve/blob/ffde3112696df688d136fc0d542d9ca4abfe6a7f/src/main/java/org/davidmoten/hilbert/Ranges.java#L30

it would allow access outside the package

**Comment by davidmoten** [comment]
I guess so. What's your use case?

**Comment by ebremer** [comment]
I've created some libraries to convert from java.awt.Polygon to org.davidmoten.hilbert.Ranges, I would like to create the reverse, but I cannot instantiate a new Ranges() without it being public.  I made the change in my fork of your library.  I could do a PR for it.

**Comment by davidmoten** [comment]
> I've created some libraries to convert from java.awt.Polygon to org.davidmoten.hilbert.Ranges, I would like to create the reverse, but I cannot instantiate a new Ranges() without it being public

I still feel in the dark about the use case but sure submit a PR.

**Comment by ebremer** [comment]
I've been converting java.awt.Polygon to a series of Range as ArrayList<Range>.  The library I wrote will take a Ranges and convert it to Polygon, but when I was doing my reverse from ArrayList<Range>, I realized I could not create Ranges because of the public constructor being missing which is why I went to ArrayList<Range> in the first place.  By making Ranges() constructor public I can eliminate ArrayList<Range> in my coding and just have two functions:
public Polygon getPolygon(Ranges r)
and
public Ranges getRanges(Polygon p)

**Comment by davidmoten** [comment]
>I've been converting java.awt.Polygon to a series of Range as ArrayList. The library I wrote will take a Ranges and convert it to Polygon, but when I was doing my reverse from ArrayList, I realized I could not create Ranges because of the public constructor being missing which is why I went to ArrayList in the first place. By making Ranges() constructor public I can eliminate ArrayList in my coding and just have two functions:
public Polygon getPolygon(Ranges r)
and
public Ranges getRanges(Polygon p)

Yep, I understood that from your first explanation but I don't understand the higher level use case. Anyway, your change is on Maven Central now 0.2.2.
