### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by jimbok8** [davidmoten/hilbert-curve#2]
Just cloned your excellent project and got a test failure!
I think it is just string formatting:

Test set: org.davidmoten.hilbert.HilbertCurveTest

Tests run: 41, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.29 sec <<< FAILURE!
testPrintOutIndexValues(org.davidmoten.hilbert.HilbertCurveTest)  Time elapsed: 0.024 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<0	1[
3	2]
> but was:<0	1[
3	2
]

`at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.davidmoten.hilbert.HilbertCurveTest.testPrintOutIndexValues(HilbertCurveTest.java:78)
`

**Comment by davidmoten** [comment]
Thanks, I'll fix. Was a bit lazy of me to check the contents of a list like that!

**Comment by davidmoten** [comment]
Righto, I've had a look. I'm assuming you ran the test on a Windows OS? If so, should be fixed now.

Please give it another try (I don't have a Windows OS handy). Cheers.

**Comment by davidmoten** [comment]
Closing, reopen if you still have problem.
