### ISSUE TITLE
Preconditions class

### ISSUE THREAD

**Issue by jimbok8** [davidmoten/hilbert-curve#3]
Can I suggest you include the Preconditions class in this project.

**Comment by davidmoten** [comment]
Any particular reason? The guava-mini dependency is 11K.

**Comment by jimbok8** [comment]
No! Just being lazy!
I was 'building with dependencies on Netbeans (Windows 7) and frustrated to
find that that class was aboumissing.
Jim

**Comment by davidmoten** [comment]
Ah, yeah trying to use libraries without maven helping you out is a tough gig these days. 

It's not just `Preconditions` but a list builder from an Iterable as well and I'd have to copy the tests over and I've then got another fork of that code to look after blah blah. So I'll leave it as it is.
