### ISSUE TITLE
maxRanges seem to not work as expected

### ISSUE THREAD

**Issue by nkoutroumanis** [davidmoten/hilbert-curve#5]
Hello David,

In the description of the repository, you mention the following example;

```
SmallHilbertCurve c = HilbertCurve.small().bits(5).dimensions(2);
long[] point1 = new long[] {3, 3};
long[] point2 = new long[] {8, 10};
// return just one range
int maxRanges = 1;
Ranges ranges = c.query(point1, point2, maxRanges);
ranges.stream().forEach(System.out::println);

```

Having the **maxRanges** variable set _1_, the returned ranges seem _4_ with the lowest and highest key _10_ and _227_ correspondingly.

Setting the *maxRanges** variable set _2_, the returned ranges seem to be _9_ with the lowest and highest key _10_ and _228_ correspondingly.

To conclude, by increasing by one (from 1 to 2), a key has been added (228). Is this expected? I suppose if I'm not mistaken, that the lowest and highest keys remain the same, regardless the maxRanges value.

Cheers,
Nick

**Comment by nkoutroumanis** [comment]
Hello David,

Any updates about this?

Nick

**Comment by davidmoten** [comment]
Thanks, I'll have a look.

**Comment by davidmoten** [comment]
I ran this:

```java
SmallHilbertCurve c = HilbertCurve.small().bits(5).dimensions(2);
long[] point1 = new long[] { 3, 3 };
long[] point2 = new long[] { 8, 10 };
{
    int maxRanges = 1;
    Ranges ranges = c.query(point1, point2, maxRanges);
    ranges.stream().forEach(System.out::println);
}
System.out.println("------------------");
{
    int maxRanges = 2;
    Ranges ranges = c.query(point1, point2, maxRanges);
    ranges.stream().forEach(System.out::println);
}
```
and got this:
```
Range [low=10, high=229]
------------------
Range [low=10, high=10]
Range [low=26, high=229]
```

Looks fine to me. Can you check again?

**Comment by nkoutroumanis** [comment]
Hm I got the same. Actually, c.query(point1, point2, maxRanges) returns for me a List<Range>, not Ranges object. Maybe, do I have a wrong version of the dependency?

Nick

**Comment by nkoutroumanis** [comment]
I was using the wrong version. I see that the latest is 0.2.1. Now everything works fine. 
I was confused because the documentation refers to the 0.1.3 version. 

Thank you very much for your time!
Nick

**Comment by davidmoten** [comment]
Ah, thanks, I've updated the README.
