### ISSUE TITLE
Increasing the Max Ranges of a Query I fetch different number of results

### ISSUE THREAD

**Issue by nkoutroumanis** [davidmoten/hilbert-curve#6]
Hello again David,

I am using your library so as to perform spatio-temporal queries.
My spatio-temporal data is enclosed to a specific spatial rectangle. 
Also, the data is extended to a specific time period.

I followed class example where you scale the points so as to get the index key.

My issue is that given a specific (big) spatio-temporal query, Itried three different max ranges (0, 70 and 100). For the three ranges, i got different (but close) number of results.
 Is this deviation expected? 

Nikos

**Comment by davidmoten** [comment]
Yes you would expect different results. The step I think that is missing is that you then filter the results to include only those items within your spatial rectangle (check each result for containment in your rectangle). After you have done that you should get the same results from each query.

**Comment by nkoutroumanis** [comment]
I do this kind of refinement you are mentioning; I filter the items within my spatial rectangle.
For the three cases, I get less results than the expected ones.

**Comment by nkoutroumanis** [comment]
Additionally, i tried another query (spatially the same area as the previous one but with a larger timespan) which works perfectly fine regardless the max ranges setting. For this one I get the expected results.

**Comment by nkoutroumanis** [comment]
I'm going to give you an example about my case, so as to find out the error.
Consider the followings;

- A space with spatial boundaries of longitude and latitude ranges ([-180, 180] and [-90,90] respectively), covering a time period with lower and upper bounds (2018-07-01T00:00:01.000, 2018-11-30T23:59:57.000).

- A SmallHilbertCurve object using 9 bits and 3 dimensions (lon, lat, time).

- A class for mapping the 3D points to the hilbert long values (resembling to yours GeoUtil class)

```
public class GeoUtil {

    public static long[] scalePoint(double lon, double minLon, double maxLon, double lat, double minLat, double maxLat, long time, long minTime, long maxTime,
                                    long max) {
        long x = scale(( lon - minLon) / (maxLon - minLon), max);
        long y = scale(( lat - minLat) / (maxLat - minLat), max);
        long z = scale(((double) time - minTime) / (maxTime - minTime), max);
        return new long[] { x, y, z };
    }

    private static long scale(double d, long max) {

        Preconditions.checkArgument(((Double.compare(d,0) > 0) || (Double.compare(d,0) == 0)) && ((Double.compare(d,1) < 0) || (Double.compare(d,1) == 0)));
        if (d == 1) {
            return max;
        } else {
            return Math.round(Math.floor(d * (max + 1)));
        }
    }

}
```

Also, consider a box _query_ with lower and upper spatial bounds (longitude, latitude) [(23.757495, 37.987295), (23.766958, 37.992997)] and temporal bounds (2018-08-25T00:00:00.000Z, 2018-08-25T23:59:59.999Z).

For the Point with coordinates (lon,lat) (23.758465, 37.98964) and timestamp 1535238729000, the hilbert value is **83145918**. The Point is enclosed by the _query_. 

Setting the maxRanges to 0, i get the hilbert values 83145921, 83145922, 83145981, 83145982, but not **83145918** as we expect.

**Comment by davidmoten** [comment]
Thanks for the detail. Can you convert your code into a failing unit test so I can study it properly?

**Comment by davidmoten** [comment]
I see three possibilities here
* a problem with the scale function
* a problem with hilbert query
* typos etc passing to these methods

You can isolate the problem yourself inasmuch as if there is a problem with the Hilbert query then forget about giving me the lat longs and times just give me the coordinates passed to the Hilbert query and the coordinate of the point that should be inside that region. Can you do that? Failing unit test is my preference of course so that I don't have to write one to be able to start work.

**Comment by nkoutroumanis** [comment]
While I was creating the test you requested, I spotted that the timestamps may be the cause of the problem. I'm checking right now for it.

**Comment by nkoutroumanis** [comment]
The problem occured because MongoDB regards the dates as ISO dates. I modified the dates on my query so as to be aligned with the dates used for producing the Hilbert index number.
Now it works perfectly. Sorry for involving you needlessly to my technical mistakes.

Τhank you very much for your time!
Nick

**Comment by davidmoten** [comment]
Great, glad you have it sorted!
