### ISSUE TITLE
`HilbertCurve.toIndex(...)` allocates too much memory

### ISSUE THREAD

**Issue by normen662** [davidmoten/hilbert-curve#68]
In line

https://github.com/davidmoten/hilbert-curve/blob/555480249ad4b3a567f525dc560e0deba220c89f/src/main/java/org/davidmoten/hilbert/HilbertCurve.java#L267

`b` is allocated with the size of `length` although if I am not mistaken, `length` is the number of bits -- not bytes. Sorry if this is incorrect! Just starting with the code...

**Comment by davidmoten** [comment]
Very nice catch, thanks! It does look like we should only need approximately length/8 bytes.

**Comment by davidmoten** [comment]
Righto, I've fixed that via PR #69. I've released [0.2.3](https://github.com/davidmoten/hilbert-curve/releases/tag/0.2.3) to Maven Central with the fix, thanks for raising the issue!
