### ISSUE TITLE
question for defining Polygon

### ISSUE THREAD

**Issue by nkoutroumanis** [davidmoten/hilbert-curve#8]
Hello David,

Are there any plans for the repository, support Polygon (comprised of points) for getting the Ranges?

Thank you,
Nikos

**Comment by davidmoten** [comment]
No plans. As it is you would use approximating rectangles covering a polygon then filter the results of the queries against the ranges for inclusion in the polygon. Does that meet your need?

**Comment by nkoutroumanis** [comment]
Yes David, I can do this by defining the MBR of the Polygon.

Thank you! :)
